return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    highlight = { enable = true },
    ensure_installed = {
      "bash",
      "c",
      "dart",
      "diff",
      "html",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "markdown",
      "markdown_inline",
      "norg",
      "norg_meta",
      "query",
      "regex",
      "vim",
      "vimdoc",
      "yaml",
    },
  },
}
